### ISSUE TITLE
Why is the downloaded video playing stuck?

### ISSUE THREAD

**Issue by jiangnoyes** [steam3d/coub-dl#1]
Why is the downloaded video playing stuck? Please tell me how to solve it?
I see the following in someone else's code to fix the first byte in the video. Is it related to this?
Code address is：https://github.com/Vladlen/coub_downloader/blob/master/coub_downloader.py
        
    def fix_first_byte_video(self, fragment):
        video_fragment = bytearray(fragment)
        video_fragment[0] = 0
        video_fragment[1] = 0
        return str(video_fragment)

    with open(self._path_to+name+".mp4", 'wb') as f:
            for chunk in video_response.iter_content(chunk_size=1024):
                if chunk: # filter out keep-alive new chunks
                    if reset_file_binary:
                        chunk = self.fix_first_byte_video(chunk)
                        reset_file_binary = False
                    f.write(chunk)

**Comment by steam3d** [comment]
Yes. You must change first byte.
```
 with open(fn,'wb') as f:
                f.write(b'\x00\x00' + dldata.read()[2:]) #dldata is source video data from coub
```
